### ISSUE TITLE
Simpler scopes?

### ISSUE THREAD

**Issue by toolmantim** [buildkite-plugins/cache-buildkite-plugin#1]
Can we make the “most basic example” in the readme even simpler, by just having a restrictive scope to start with? Or is there a way to SHA256 things and fully trust the manifest?

For yarn and bundler and things, the only things to bust a SHA256 manifest would be an arch difference between agent machines for native deps.

**Comment by toote** [comment]
#27 changed scopes to plugin levels (keeping the `manifest file` idea as the most basic level)
