### ISSUE TITLE
Error with S3 backend: "Unknown options: --recursive"

### ISSUE THREAD

**Issue by geoffharcourt** [buildkite-plugins/cache-buildkite-plugin#29]
We're running the Elastic CI stack v5.16.1 and trying to use the S3 storage option. At the end of our build, during the cache plugin's `post-command` hook, we're getting this error:

```
Running plugin cache post-command hook | 0s
-- | --
  | $ /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-cache-buildkite-plugin-v0-3-0/hooks/post-command
  | Saving file-level cache of /bundle
  |  
  | Unknown options: --recursive
  | 🚨 Error: The plugin cache post-command hook exited with status 255

```

It looks like the flag is being passed in here: https://github.com/buildkite-plugins/cache-buildkite-plugin/blob/master/backends/cache_s3#L22-L26

Are we doing something wrong?

**Comment by toote** [comment]
Nope... completely our fault. I originally implemented it using `cp` instead of `sync` and forgot to remove that flag afterwards :(
