### ISSUE TITLE
Support for backend: artifacts

### ISSUE THREAD

**Issue by TSMMark** [buildkite-plugins/cache-buildkite-plugin#34]
Is there a reason buildkite artifacts are not a suitable backend for this?

I read

> Buildkite recommends using [Artifacts](https://buildkite.com/docs/builds/artifacts) for build artifacts that are the result of a build and useful for humans, where as we see cache as being an optional byproduct of builds that doesn't need to be content addressable.

but that doesn't explain why we shouldn't/can't use artifacts as the backend for this. To me that seems like a more suitable and native buildkite integration, than relying on S3 for remote caching.

**Comment by toote** [comment]
The main issue I can see with this is the fact that artifacts are not a _filesystem_-like repository of information so the interface for the required operations can be kind of weird. For example, multiple steps can upload artifacts with the same name and trying to [download an artifact with that name will result in an error](https://buildkite.com/docs/pipelines/artifacts#troubleshooting-a-multiple-artifacts-were-found-for-query-error) unless you add more parameters (like step or build).

That said, if you want to give it a go to try to implement it, we will be more than happy to test and review any PR you create :)

**Comment by timnolte** [comment]
Wouldn't this also be an issue in practice since Buildkite artifacts are captured only at the build level not pipeline level. This would mean having to attempt to know what build ID to pull artifacts from. If you are simply using the cache across steps in a single build then it seems like you could just use artifacts.
