### ISSUE TITLE
S3 backend fails to sync with `tgz` compression

### ISSUE THREAD

**Issue by DavidGregory084** [buildkite-plugins/cache-buildkite-plugin#52]
The S3 backend is unable to sync when using `tgz` compression:

![image](https://github.com/buildkite-plugins/cache-buildkite-plugin/assets/2992938/81367bbe-5f14-49e2-a0d8-9386f313f215)

I think this is because the `s3 sync` command does not expect to receive a single file as argument, so it tries to find a directory with the same name instead. Perhaps it should create a temporary directory in /tmp and archive a .tgz file named after the cache key into that temporary directory instead, i.e. 

```bash
ACTUAL_PATH="$(mktemp -d)"
"${COMPRESS_COMMAND[@]}" "${ACTUAL_PATH}/${KEY}.tgz" "${CACHE_PATH}"
```

I was able to replicate this on the build agent host manually:

```bash
$ ACTUAL_PATH=$(mktemp)
$ echo $ACTUAL_PATH 
/tmp/tmp.WUc3AxyL2d
$ tar czf "$ACTUAL_PATH" .gradle
$ aws s3 sync --endpoint-url "https://data.mina-lang.org" "$ACTUAL_PATH" "s3://buildkite-cache/test-key"          
warning: Skipping file /tmp/tmp.WUc3AxyL2d/. File does not exist.
```

The pipeline YAML can be viewed [here](https://codeberg.org/mina-lang/mina/src/commit/e321ed0d8a3a22894910cf708e764f8bbdf67678/.buildkite/pipeline.yml).

You can view a gist of a build log exhibiting this problem [here](https://gist.github.com/DavidGregory084/bf17b49962cf524e7f01ac27eb9f8aba).

One other thing that I noticed in this log is that the second cache post-command hook did not run after the first one failed. Is that expected?

**Comment by surajthakur** [comment]
We are facing the same issue, waiting for the fix.

**Comment by surajthakur** [comment]
Hi @pzeballos , 
We are also facing the same issue. We want to start using the cache plugin but without compression, cant use the plugin for `node_modules` as without compression, it take ages to copy files. 

Any ideas on the timeline, when the fix will be released, so we dont plan any custom fixes. 

Thanks
Regards
Suraj

**Comment by dotnich-io** [comment]
I'm experiencing this error too.
