### ISSUE TITLE
Is `fs` backend supposed to work with EBS?

### ISSUE THREAD

**Issue by smsunarto** [buildkite-plugins/cache-buildkite-plugin#64]
It seems like using the `fs` backend keeps failing with the following error (the directory exists and `s3` backend works just fine)

```
Waiting for folder lock
Waiting for folder lock
Waiting for folder lock
Waiting for folder lock
Waiting for folder lock
```

I'm guessing this might have something to do with using AWS EBS instead of built-in NVMe storage?

**Comment by toote** [comment]
@smsunarto the `fs` store should work no matter where the filesystem is stored (be it NVMe instance store or EBS). There are 3 situations I can think of that would cause that behaviour:

1- there is another job in an agent on the same machine actually running parts of the cache code that acquires the lock (which is the whole reason locks are there in the first place)
2- something happened while running the plugin's hooks (like a cancelled or timed-out step) that caused the locks to remain around despite not being needed (solution here would be to manually clear the files, wipe the the cache folder or start with a brand-new instance)
3- an actual bug (in which case we will probably need more steps to reproduce the behaviour)

**Comment by pzeballos** [comment]
@smsunarto, we noticed that we were throwing that message if you didn't have `BUILDKITE_PLUGIN_FS_CACHE_FOLDER` configured (#54 ). We made some changes to improve the error (#68). Are you still experiencing issues?
