### ISSUE TITLE
Skip compression if cache already exists

### ISSUE THREAD

**Issue by askoufis** [buildkite-plugins/cache-buildkite-plugin#78]
I've noticed that compression occurs regardless of whether the cache ends up being pushed to the backend:

https://github.com/buildkite-plugins/cache-buildkite-plugin/blob/d0177d1afda90a6f0beff16f1a4e1ebf6d4391bc/hooks/post-command#L42-L59

It would be nice to avoid compression if the cache already exists in the backend.

**Comment by toote** [comment]
This was implemented in #85
